image: docker:latest
services:
  - docker:dind

stages:
  - build
  - push
  - deploy

#production
build:
  stage: build
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.master.yml build --no-cache
    - docker-compose -f docker-compose.master.yml push 
  tags: [docker]
  only:
    - staging
    - master
    - docker

deploy:
  stage: deploy
  tags: [deploy]
  script:
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.master.yml down -v --rmi all
    - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo docker-compose -f docker-compose.master.yml pull
    - sudo docker-compose -f docker-compose.master.yml up -d
  only:
    - master
    - staging
